export default function LlmDisclaimer() {
  return (
    <footer
      className="shrink-0 border-t border-border-gold/40 bg-panel/95 px-4 py-2.5 text-center backdrop-blur-sm"
      role="note"
      aria-label="AI disclaimer"
    >
      <p className="text-[11px] leading-relaxed text-parchment/70 sm:text-xs">
        <span className="font-medium text-gold-dim">Disclaimer:</span> Questions,
        explanations, and feedback are generated by AI and may be incorrect or
        incomplete. Always verify important information against your source
        material.
      </p>
    </footer>
  );
}
